server:
  port: 8001

spring:
  application:
    name: quoteservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000 # <- din auth-server

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
